### ISSUE TITLE
Is it possible to use this project locally ?

### ISSUE THREAD

**Issue by JeromeVi** [ardoq/ardoq-docker-compose-addon#4]
Hi,
I need to find a way to generate a graphic of a docker-compose.yml file. I need to show the ports, the volumes and the containers with their depencies.
Your project look great for that but as I see we can't use it locally ? We can only see the graph on your website ?

I would like to create the graph and store it manually like with this one for example https://github.com/funkwerk/compose_plantuml

**Comment by kristianhelgesen** [comment]
We're a cloud platform, so you don't have the option to run it locally. You can however download the visualisation after you have imported your project to Ardoq. https://ardoq.com/help/export-2/

Also please note that we haven't released support for Dockerfile version 3 yet.
